name: Task
description: Create a new task assignment
title: "[Task]: "
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: Describe the task in detail...
    validations:
      required: true
  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      description: What is the expected output?
      placeholder: |
        - [ ] Deliverable 1
        - [ ] Deliverable 2
    validations:
      required: true
  - type: input
    id: deadline
    attributes:
      label: Deadline
      description: When is this due? (optional)
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
  - type: input
    id: dependencies
    attributes:
      label: Dependencies
      description: Does this depend on other issues? (optional)
      placeholder: "#1, #2"
    validations:
      required: false
